#!/bin/bash

apt update && apt upgrade -y

if [[ -n "$PREFIX" ]] ; then
    command="pkg install"
    apt update && apt upgrade -y
else
    PREFIX="/usr"
    command="sudo apt install"
    sudo apt update && apt upgrade -y
fi

$command phpmyadmin php-apache mariadb apache2

function set_config_apache2(){
   if [[ -r $PREFIX/etc/apache2 ]] ; then
      if [[ -f $PREFIX/etc/apache2/httpd.conf ]]; then
         mv $PREFIX/etc/apache2/httpd.conf $PREFIX/etc/apache2/httpd.conf.bak
      fi
      cp httpd.conf $PREFIX/etc/apache2/
      echo -e "\e[1;96mhttpd.conf added Succesfully ! \e[0m " 
   fi
}

function install_mysql(){
    if [[ ! -d  $PREFIX/etc/my.cnf.d ]] ; then
       mkdir $PREFIX/etc/my.cnf.d
       mysql_install_db
    fi
}

function set_phpmyadmin(){
    sed -i "s/localhost/127.0.0.1/" $PREFIX/share/phpmyadmin/config.inc.php
}

function set_env(){
   if [[ -f `pwd`/xamp ]] ; then
   chmod +x xamp && cp xamp $PREFIX/bin/
   fi
}
install_mysql && set_phpmyadmin && set_config_apache2
set_env

